config/routes.rb
Task::Application.routes.draw do

  devise_for :users

  resources :entries

  root :to => "entries#index"
end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < InheritedResources::Base
  before_filter :authenticate_user!,  :except => [:index, :show]

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.slim
= simple_form_for @entry do |f|
  div
    = f.input :title, :label => 'Title'
  div
    = f.input :body, :label => 'Details'
  div
    = f.submit 'Save'

app/views/entries/edit.slim
h2 Edit

= render :partial => 'form'

app/views/entries/index.slim
h2 Listing entries
div
  ul
    - collection.each do |t|
      li
        =link_to t.title, entry_path(t)
        ul
          li
            = link_to "Edit", edit_entry_path(t)
          li
            = link_to "Delete", t, :method => :delete, :class => :delete, :confirm => 'Are you sure?'

app/views/entries/new.slim
h2 New

= render :partial => 'form'

app/views/entries/show.slim
div
  h2
    =resource.title
div
  p
    =resource.body

app/views/layouts/application.slim
doctype 5
html
  head
    title Application Demo
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag

  body
    header
      = render "shared/menu"

    #content
      =yield

    footer

app/views/shared/_menu.slim
ul
  li
    =link_to "Home", entries_path
  li
    =link_to "New entry", new_entry_path
  - if current_user
    li 
      = link_to 'Logout', destroy_user_session_path, :method => :delete
  - else
    li 
      = link_to 'Sign Up', new_user_registration_path
    li
      = link_to 'Sign In', new_user_session_path

app/views/user/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>